version: "3.9"

services:
  airflow:
    build: .
    volumes:
      - ./crawler:/root/airflow/dags
    ports:
      - "8080:8080"

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=git
      - POSTGRES_DB=OLX
    ports:
      - "5432:5432"

  metabase:
    image: metabase/metabase:latest
    volumes:
      - ./metabase-data:/metabase-data
    ports:
      - "3000:3000"
    depends_on:
      - postgres
