version: "3.9"

services:
  airflow:
    build: .
    volumes:
      - ./crawler:/root/airflow/dags
    ports:
      - "8080:8080"

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456789
      - POSTGRES_DB=OLX
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  metabase:
    image: metabase/metabase:latest
    volumes:
      - ./metabase-data:/metabase-data
    environment:
      - MB_DB_FILE=/metabase-data/metabase.db
    ports:
      - "3000:3000"

volumes:
  postgres-data:
  metabase-data:
